---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: doppler
spec:
  conditions:
    - namespaces:
        - external-secrets
        - media
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            key: dopplerToken
            name: doppler-token
            namespace: external-secrets
      config: prd_kubernetes
      project: home-cluster
