---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflare-tunnel
spec:
  chartRef:
    kind: OCIRepository
    name: cloudflare-tunnel
  interval: 1h
  values:
    defaultPodOptions:
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault

    configMaps:
      config:
        data:
          config.yaml: |-
            ingress:
              - hostname: "*.idahobealefamily.com"
                originRequest:
                  http2Origin: true
                  keepAliveTimeout: 3600s
                  originServerName: external.idahobealefamily.com
                  tcpKeepAlive: 7200s
                service: https://envoy-external.{{ .Release.Namespace }}.svc.cluster.local:443
              - service: http_status:404

    controllers:
      cloudflare-tunnel:
        annotations:
          reloader.stakater.com/auto: "true"

        replicas: 1
        strategy: RollingUpdate

        containers:
          cloudflare-tunnel:
            image:
              repository: docker.io/cloudflare/cloudflared
              tag: 2026.10.0@sha256:9b49eed8f62806d5d45ddf59ecefb5710429598ea6d3fcccd2af938f621b2b07

            args:
              - tunnel
              - run

            env:
              NO_AUTOUPDATE: true
              TUNNEL_METRICS: 0.0.0.0:8080

            envFrom:
              - secretRef:
                  name: cloudflare-tunnel-secret

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  failureThreshold: 3
                  httpGet:
                    path: /ready
                    port: &port 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
              readiness: *probes
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi

            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - "ALL"
              readOnlyRootFilesystem: true

    externalSecrets:
      cloudflare-tunnel-secret:
        enabled: true
        dataFrom:
          - extract:
              key: CLOUDFLARE
        refreshInterval: 12h
        secretStoreRef:
          kind: ClusterSecretStore
          name: doppler
        target:
          creationPolicy: Owner
          deletionPolicy: Delete
          name: cloudflare-tunnel-secret
          template:
            data:
              TUNNEL_TOKEN: |-
                {{ toJson (dict "a" .CLOUDFLARE_ACCOUNT_ID "t" .CLOUDFLARE_TUNNEL_ID "s" .CLOUDFLARE_TUNNEL_SECRET) | b64enc }}
            engineVersion: v2

    persistence:
      config-file:
        type: configMap
        identifier: config
        globalMounts:
          - path: /etc/cloudflared/config.yaml
            readOnly: true
            subPath: config.yaml

    service:
      cloudflare-tunnel:
        controller: cloudflare-tunnel
        ports:
          http:
            port: *port

    serviceMonitor:
      cloudflare-tunnel:
        endpoints:
          - port: http
        serviceName: cloudflare-tunnel
