---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tautulli
spec:
  chartRef:
    kind: OCIRepository
    name: tautulli
  interval: 1h
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000

    controllers:
      tautulli:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          tautulli:
            image:
              repository: ghcr.io/home-operations/tautulli
              tag: 2.18.1@sha256:2cc92abed174f89d4fa75ab98e39af0114f37829e9c675718b264cc80931c4f5

            env:
              TAUTULLI_HTTP_BASE_URL: https://tautulli.idahobealefamily.com
              TAUTULLI_HTTP_PORT: &port 8181
              TZ: America/Boise

            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"

            probes:
              liveness: &probes
                enabled: false
                custom: true
                spec:
                  failureThreshold: 3
                  httpGet:
                    path: /status
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
              readiness: *probes

            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi

            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - "ALL"
              readOnlyRootFilesystem: true

    externalSecrets:
      tautulli:
        enabled: true
        data:
          - remoteRef:
              key: TAUTULLI_API_KEY
            secretKey: TAUTULLI_API_KEY
        refreshInterval: 12h
        secretStoreRef:
          kind: ClusterSecretStore
          name: doppler
        target:
          creationPolicy: Owner
          deletionPolicy: Delete
          name: tautulli-secret
          template:
            data:
              TAUTULLI_API_KEY: "{{ .TAUTULLI_API_KEY }}"
            engineVersion: v2

    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"

      tmpfs:
        type: emptyDir
        advancedMounts:
          tautulli:
            tautulli:
              - path: /config/logs
                subPath: logs
              - path: /tmp
                subPath: tmp

    route:
      tautulli:
        enabled: true
        hostnames:
          - "{{ .Release.Name }}.idahobealefamily.com"
        parentRefs:
          - name: envoy-external
            namespace: networking
        rules:
          - backendRefs:
              - identifier: tautulli
                port: *port

    service:
      tautulli:
        controller: tautulli
        ports:
          http:
            port: *port
