---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: recyclarr
spec:
  chartRef:
    kind: OCIRepository
    name: recyclarr
  interval: 1h
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000

    controllers:
      recyclarr:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          recyclarr:
            image:
              repository: ghcr.io/recyclarr/recyclarr
              tag: 8.7.3@sha256:9c6c74d52cfc6f740a5a3624aa83867e171bb70b90453ddb7a4048b8c80445f9

            env:
              RECYCLARR_DATA_DIR: /tmp

              TZ: America/Boise
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"

            resources:
              requests:
                cpu: 5m
                memory: 36M
              limits:
                memory: 128M

            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - "ALL"

              readOnlyRootFilesystem: true

    externalSecrets:
      recyclarr:
        dataFrom:
          - extract:
              key: RADARR
          - extract:
              key: SONARR
        refreshInterval: 12h
        secretStoreRef:
          kind: ClusterSecretStore
          name: doppler
        target:
          creationPolicy: Owner
          deletionPolicy: Delete
          name: recyclarr-secret

    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"

      recyclarr-configs:
        type: configMap
        name: recyclarr-configs
        globalMounts:
          - path: /config/configs/sonarr-config.yaml
            subPath: sonarr-config.yaml

          - path: /config/configs/sonarr-anime-config.yaml
            subPath: sonarr-anime-config.yaml

          - path: /config/configs/sonarr-uhd-config.yaml
            subPath: sonarr-uhd-config.yaml

          - path: /config/configs/radarr-config.yaml
            subPath: radarr-config.yaml

          - path: /config/configs/radarr-anime-config.yaml
            subPath: radarr-anime-config.yaml

          - path: /config/configs/radarr-uhd-config.yaml
            subPath: radarr-uhd-config.yaml

      tmp:
        type: emptyDir

    service:
      recyclarr:
        enabled: false
        controller: recyclarr
