---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: echo-server
spec:
  chartRef:
    kind: OCIRepository
    name: echo-server
  interval: 1h
  values:
    controllers:
      echo-server:
        containers:
          echo-server:
            image:
              repository: ghcr.io/mendhak/http-https-echo
              tag: 42

            env:
              HTTP_PORT: &port 8080
              LOG_IGNORE_PATH: "/healthz"
              LOG_WITHOUT_NEWLINE: "true"
              TZ: America/Boise

            probes:
              liveness: &probes
                enabled: true
              readiness: *probes
              startup: *probes

            resources:
              requests:
                cpu: 5m
                memory: 64M
              limits:
                memory: 64M

    route:
      echo-server:
        enabled: true
        hostnames:
          - "{{ .Release.Name }}.idahobealefamily.com"
        parentRefs:
          - name: envoy-internal
            namespace: networking

    service:
      echo-server:
        controller: echo-server
        ports:
          http:
            port: *port
