---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: alertmanager-secret
  data:
    - secretKey: DISCORD_WEBHOOK_URL
      remoteRef:
        key: DISCORD_WEBHOOK_URL
