---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
spec:
  chartRef:
    kind: OCIRepository
    name: homepage
  interval: 1h
  values:
    defaultPodOptions:
      automountServiceAccountToken: true
      hostUsers: false

    controllers:
      homepage:
        annotations:
          reloader.stakater.com/auto: "true"

        strategy: RollingUpdate

        containers:
          homepage:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v2.4.0@sha256:643bd0be730d40f69d58028a55d1a896739333e8815786df42bc97f109ecbe61

            env:
              HOMEPAGE_ALLOWED_HOSTS: "{{ .Release.Name }}.idahobealefamily.com"

              TZ: America/Boise
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"

            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true

            resources:
              requests:
                cpu: 15m
                memory: 200M
              limits:
                memory: 2G

            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: false

    externalSecrets:
      homepage:
        data:
          - remoteRef:
              key: PFSENSE_API_KEY
            secretKey: PFSENSE_API_KEY
          - remoteRef:
              key: PROWLARR_APIKEY
            secretKey: PROWLARR_APIKEY
          - remoteRef:
              key: SEERR_API_KEY
            secretKey: SEERR_API_KEY
          - remoteRef:
              key: TAUTULLI_API_KEY
            secretKey: TAUTULLI_API_KEY
          - remoteRef:
              key: TRUENAS_AUDIT_API_KEY
            secretKey: TRUENAS_AUDIT_API_KEY
        dataFrom:
          - extract:
              key: CLOUDFLARE
          - extract:
              key: SABNZBD
          - extract:
              key: COMMON
          - extract:
              key: PROXMOX
          - extract:
              key: RADARR
          - extract:
              key: SONARR
          - extract:
              key: HOME
        refreshInterval: 12h
        secretStoreRef:
          kind: ClusterSecretStore
          name: doppler
        target:
          creationPolicy: Owner
          name: homepage-secret
          template:
            data:
              HOMEPAGE_VAR_CLOUDFLARE_ACCOUNT_ID: "{{ .CLOUDFLARE_ACCOUNT_ID }}"
              HOMEPAGE_VAR_CLOUDFLARE_HOMEPAGE_API_TOKEN: "{{ .CLOUDFLARE_HOMEPAGE_API_TOKEN }}"
              HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_ID: "{{ .CLOUDFLARE_TUNNEL_ID }}"
              HOMEPAGE_VAR_GRAFANA_ADMIN_PASSWORD: "{{ .ADMIN_PASSWORD }}"
              HOMEPAGE_VAR_GRAFANA_ADMIN_USER: "{{ .ADMIN_USER }}"
              HOMEPAGE_VAR_LATITUDE: "{{ .LATITUDE }}"
              HOMEPAGE_VAR_LONGITUDE: "{{ .LONGITUDE }}"
              HOMEPAGE_VAR_OMADA_ADMIN_PASSWORD: "{{ .ADMIN_PASSWORD }}"
              HOMEPAGE_VAR_OMADA_ADMIN_USER: "{{ .ADMIN_USER }}"
              HOMEPAGE_VAR_PFSENSE_API_KEY: "{{ .PFSENSE_API_KEY }}"
              HOMEPAGE_VAR_PROWLARR_APIKEY: "{{ .PROWLARR_APIKEY }}"
              HOMEPAGE_VAR_PROXMOX_TOKEN_ID: "{{ .homepage_token_id }}"
              HOMEPAGE_VAR_PROXMOX_TOKEN_SECRET: "{{ .homepage_token_secret }}"
              HOMEPAGE_VAR_RADARR_ANIME_APIKEY: "{{ .RADARR_ANIME_APIKEY }}"
              HOMEPAGE_VAR_RADARR_APIKEY: "{{ .RADARR_APIKEY }}"
              HOMEPAGE_VAR_RADARR_UHD_APIKEY: "{{ .RADARR_UHD_APIKEY }}"
              HOMEPAGE_VAR_SABNZBD_API_KEY: "{{ .SABNZBD_API_KEY }}"
              HOMEPAGE_VAR_SEERR_API_KEY: "{{ .SEERR_API_KEY }}"
              HOMEPAGE_VAR_SONARR_ANIME_APIKEY: "{{ .SONARR_ANIME_APIKEY }}"
              HOMEPAGE_VAR_SONARR_APIKEY: "{{ .SONARR_APIKEY }}"
              HOMEPAGE_VAR_SONARR_UHD_APIKEY: "{{ .SONARR_UHD_APIKEY }}"
              HOMEPAGE_VAR_TAUTULLI_API_KEY: "{{ .TAUTULLI_API_KEY }}"
              HOMEPAGE_VAR_TRUENAS_AUDIT_API_KEY: "{{ .TRUENAS_AUDIT_API_KEY }}"
            engineVersion: v2

    persistence:
      config:
        type: configMap
        name: homepage-config
        globalMounts:
          - path: /app/config/bookmarks.yaml
            subPath: bookmarks.yaml
          - path: /app/config/docker.yaml
            subPath: docker.yaml
          - path: /app/config/kubernetes.yaml
            subPath: kubernetes.yaml
          - path: /app/config/proxmox.yaml
            subPath: proxmox.yaml
          - path: /app/config/services.yaml
            subPath: services.yaml
          - path: /app/config/settings.yaml
            subPath: settings.yaml
          - path: /app/config/widgets.yaml
            subPath: widgets.yaml

      tmpfs:
        type: emptyDir
        advancedMounts:
          homepage:
            homepage:
              - path: /app/config/logs
                subPath: logs
              - path: /tmp
                subPath: tmp

    rbac:
      bindings:
        clusterrolebinding:
          enabled: true
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: homepage
          subjects:
            - kind: ServiceAccount
              name: homepage
              namespace: web-tools
          type: ClusterRoleBinding

      roles:
        clusterrole:
          enabled: true
          rules:
            - apiGroups:
                - ""
              resources:
                - namespaces
                - pods
                - nodes
              verbs:
                - get
                - list
            - apiGroups:
                - extensions
                - networking.k8s.io
              resources:
                - ingresses
              verbs:
                - get
                - list
            - apiGroups:
                - metrics.k8s.io
              resources:
                - nodes
                - pods
              verbs:
                - get
                - list
            - apiGroups:
                - gateway.networking.k8s.io
              resources:
                - gateways
                - httproutes
              verbs:
                - get
                - list
            - apiGroups:
                - apiextensions.k8s.io
              resources:
                - customresourcedefinitions/status
              verbs:
                - get
                - list
            - apiGroups:
                - metrics.k8s.io
              resources:
                - nodes
                - pods
              verbs:
                - get
                - list
          type: ClusterRole

    route:
      homepage:
        enabled: true
        hostnames:
          - "{{ .Release.Name }}.idahobealefamily.com"
        parentRefs:
          - name: envoy-internal
            namespace: networking
        rules:
          - backendRefs:
              - identifier: homepage
                port: &port 3000

    service:
      homepage:
        controller: homepage
        ports:
          http:
            port: *port
